version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-hexagonal
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: hexagonalarchitecturedb
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --init-connect='SET time_zone="+00:00";'

volumes:
  mysql_data:
    driver: local
